title: Maryam El B ® # your name (or website title) here
logo: /images/profile.png # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, this is Maryam
  <br>Welcome to my portfolio where I will walk you through the projects I've worked on.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/maryam-el-b-00738a220">View My LinkedIn Profile</a> 
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
